#############################################################################
# Makefile for building: dsmc
# Generated by qmake (3.0) (Qt 5.1.1) on: Wed Oct 30 17:16:28 2013
# Project:  program/dsmc/dsmc.pro
# Template: app
# Command: /Users/anderhaf/Qt5.1.1/5.1.1/clang_64/bin/qmake -spec macx-clang CONFIG+=x86_64 -o Makefile program/dsmc/dsmc.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = mpicc
CXX           = /usr/bin/icpc
DEFINES       = 
CFLAGS        = -pipe -O2 -isysroot /Applications/Xcode5-DP2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -mmacosx-version-min=10.6 -Wall -W -fPIE $(DEFINES)
CXXFLAGS      = -pipe -DMPICH_IGNORE_CXX_SEEK -pipe -fast -pipe -DMPICH_IGNORE_CXX_SEEK -isysroot /Applications/Xcode5-DP2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -mmacosx-version-min=10.6 -Wall -W -fPIE $(DEFINES)
INCPATH       = -I/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/macx-clang -Iprogram/dsmc -I/usr/local/include -I.
LINK          = /usr/bin/icpc
LFLAGS        = -headerpad_max_install_names -Wl,-syslibroot,/Applications/Xcode5-DP2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -mmacosx-version-min=10.6
LIBS          = $(SUBLIBS)  
AR            = /Applications/Xcode5-DP2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode5-DP2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
QMAKE         = /Users/anderhaf/Qt5.1.1/5.1.1/clang_64/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = program/dsmc/main.cpp \
		program/dsmc/system.cpp \
		program/dsmc/cell.cpp \
		program/dsmc/statisticssampler.cpp \
		program/dsmc/random.cpp \
		program/dsmc/grid.cpp \
		program/dsmc/cutil.cpp \
		program/dsmc/unitconverter.cpp \
		program/dsmc/settings.cpp \
		program/dsmc/dsmc_io.cpp \
		program/dsmc/dsmctimer.cpp \
		program/dsmc/moleculemover.cpp \
		program/dsmc/colliderbase.cpp \
		program/dsmc/colliderspecular.cpp \
		program/dsmc/colliderthermal.cpp \
		program/dsmc/collidercercignanilampis.cpp \
		program/dsmc/collidermaxwell.cpp \
		program/dsmc/cvector.cpp \
		program/dsmc/topology.cpp \
		program/dsmc/visualizer.cpp \
		program/dsmc/testshader.cpp \
		program/dsmc/solver.cpp \
		program/dsmc/progressbar.cpp \
		program/dsmc/perlin.cpp \
		program/dsmc/oglshader.cpp \
		program/dsmc/moviedata.cpp \
		program/dsmc/movie.cpp \
		program/dsmc/mesh.cpp \
		program/dsmc/marchingcubes.cpp \
		program/dsmc/ctexture.cpp \
		program/dsmc/cshaders.cpp \
		program/dsmc/copengl.cpp \
		program/dsmc/complexgeometry.cpp \
		program/dsmc/combined.cpp \
		program/dsmc/cmath.cpp \
		program/dsmc/citmap.cpp \
		program/dsmc/cisosurface.cpp \
		program/dsmc/cbitmap.cpp \
		program/dsmc/camera.cpp \
		program/dsmc/geometry.cpp \
		program/dsmc/diamondsquare.cpp 
OBJECTS       = main.o \
		system.o \
		cell.o \
		statisticssampler.o \
		random.o \
		grid.o \
		cutil.o \
		unitconverter.o \
		settings.o \
		dsmc_io.o \
		dsmctimer.o \
		moleculemover.o \
		colliderbase.o \
		colliderspecular.o \
		colliderthermal.o \
		collidercercignanilampis.o \
		collidermaxwell.o \
		cvector.o \
		topology.o \
		visualizer.o \
		testshader.o \
		solver.o \
		progressbar.o \
		perlin.o \
		oglshader.o \
		moviedata.o \
		movie.o \
		mesh.o \
		marchingcubes.o \
		ctexture.o \
		cshaders.o \
		copengl.o \
		complexgeometry.o \
		combined.o \
		cmath.o \
		citmap.o \
		cisosurface.o \
		cbitmap.o \
		camera.o \
		geometry.o \
		diamondsquare.o
DIST          = /Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/features/spec_pre.prf \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/qdevice.pri \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/features/device_config.prf \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/common/shell-unix.conf \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/common/unix.conf \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/common/mac.conf \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/common/macx.conf \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/common/gcc-base.conf \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/common/gcc-base-mac.conf \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/common/clang.conf \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/common/clang-mac.conf \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/qconfig.pri \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_3d.pri \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_clucene.pri \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_core.pri \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_designer.pri \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_designercomponents.pri \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_gui.pri \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_help.pri \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_network.pri \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_platformsupport.pri \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_qml.pri \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_qmldevtools.pri \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_quick.pri \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_quickparticles.pri \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_script.pri \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_sql.pri \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_svg.pri \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_v8.pri \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_xml.pri \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/features/qt_functions.prf \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/features/qt_config.prf \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/macx-clang/qmake.conf \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/features/spec_post.prf \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/features/exclusive_builds.prf \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/features/default_pre.prf \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/features/unix/default_pre.prf \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/features/mac/default_pre.prf \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/features/resolve_config.prf \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/features/default_post.prf \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/features/mac/sdk.prf \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/features/mac/default_post.prf \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/features/mac/objective_c.prf \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/features/warn_on.prf \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/features/mac/rez.prf \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/features/testcase_targets.prf \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/features/exceptions.prf \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/features/yacc.prf \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/features/lex.prf \
		program/dsmc/program/dsmc/dsmc.pro \
		program/dsmc/dsmc.pro
QMAKE_TARGET  = dsmc
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = dsmc

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-O2 \
		-isysroot \
		/Applications/Xcode5-DP2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk \
		-mmacosx-version-min=10.6 \
		-Wall \
		-W



first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: program/dsmc/dsmc.pro /Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/macx-clang/qmake.conf /Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/features/spec_pre.prf \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/qdevice.pri \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/features/device_config.prf \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/common/shell-unix.conf \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/common/unix.conf \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/common/mac.conf \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/common/macx.conf \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/common/gcc-base.conf \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/common/gcc-base-mac.conf \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/common/clang.conf \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/common/clang-mac.conf \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/qconfig.pri \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_3d.pri \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_clucene.pri \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_core.pri \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_designer.pri \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_designercomponents.pri \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_gui.pri \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_help.pri \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_network.pri \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_platformsupport.pri \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_qml.pri \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_qmldevtools.pri \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_quick.pri \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_quickparticles.pri \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_script.pri \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_sql.pri \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_svg.pri \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_v8.pri \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_xml.pri \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/features/qt_functions.prf \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/features/qt_config.prf \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/macx-clang/qmake.conf \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/features/spec_post.prf \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/features/exclusive_builds.prf \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/features/default_pre.prf \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/features/unix/default_pre.prf \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/features/mac/default_pre.prf \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/features/resolve_config.prf \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/features/default_post.prf \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/features/mac/sdk.prf \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/features/mac/default_post.prf \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/features/mac/objective_c.prf \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/features/warn_on.prf \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/features/mac/rez.prf \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/features/testcase_targets.prf \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/features/exceptions.prf \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/features/yacc.prf \
		/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/features/lex.prf \
		program/dsmc/dsmc.pro
	$(QMAKE) -spec macx-clang CONFIG+=x86_64 -o Makefile program/dsmc/dsmc.pro
/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/features/spec_pre.prf:
/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/qdevice.pri:
/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/features/device_config.prf:
/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/common/shell-unix.conf:
/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/common/unix.conf:
/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/common/mac.conf:
/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/common/macx.conf:
/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/common/gcc-base.conf:
/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/common/gcc-base-mac.conf:
/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/common/clang.conf:
/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/common/clang-mac.conf:
/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/qconfig.pri:
/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_3d.pri:
/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_clucene.pri:
/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_core.pri:
/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_declarative.pri:
/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_designer.pri:
/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_designercomponents.pri:
/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_gui.pri:
/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_help.pri:
/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_network.pri:
/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_opengl.pri:
/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_platformsupport.pri:
/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_qml.pri:
/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_qmldevtools.pri:
/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri:
/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_quick.pri:
/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_quickparticles.pri:
/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_script.pri:
/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_sensors.pri:
/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_serialport.pri:
/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_sql.pri:
/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_svg.pri:
/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_testlib.pri:
/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_uitools.pri:
/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_v8.pri:
/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_webkit.pri:
/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_widgets.pri:
/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_xml.pri:
/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/features/qt_functions.prf:
/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/features/qt_config.prf:
/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/macx-clang/qmake.conf:
/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/features/spec_post.prf:
/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/features/exclusive_builds.prf:
/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/features/default_pre.prf:
/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/features/unix/default_pre.prf:
/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/features/mac/default_pre.prf:
/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/features/resolve_config.prf:
/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/features/default_post.prf:
/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/features/mac/sdk.prf:
/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/features/mac/default_post.prf:
/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/features/mac/objective_c.prf:
/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/features/warn_on.prf:
/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/features/mac/rez.prf:
/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/features/testcase_targets.prf:
/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/features/exceptions.prf:
/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/features/yacc.prf:
/Users/anderhaf/Qt5.1.1/5.1.1/clang_64/mkspecs/features/lex.prf:
program/dsmc/dsmc.pro:
qmake: FORCE
	@$(QMAKE) -spec macx-clang CONFIG+=x86_64 -o Makefile program/dsmc/dsmc.pro

qmake_all: FORCE

dist: 
	@test -d .tmp/dsmc1.0.0 || mkdir -p .tmp/dsmc1.0.0
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/dsmc1.0.0/ && (cd `dirname .tmp/dsmc1.0.0` && $(TAR) dsmc1.0.0.tar dsmc1.0.0 && $(COMPRESS) dsmc1.0.0.tar) && $(MOVE) `dirname .tmp/dsmc1.0.0`/dsmc1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/dsmc1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

main.o: program/dsmc/main.cpp program/dsmc/system.h \
		program/dsmc/cinifile.h \
		program/dsmc/cutil.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/mpi.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/mpi_portable_platform.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/mpicxx.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/constants.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/functions.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/datatype.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/exception.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/op.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/status.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/request.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/group.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/comm.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/win.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/file.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/errhandler.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/intracomm.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/topology.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/intercomm.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/info.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/datatype_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/functions_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/request_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/comm_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/intracomm_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/topology_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/intercomm_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/group_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/op_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/errhandler_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/status_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/info_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/win_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/file_inln.h \
		program/dsmc/statisticssampler.h \
		program/dsmc/unitconverter.h \
		program/dsmc/settings.h \
		program/dsmc/dsmc_io.h \
		program/dsmc/dsmctimer.h \
		program/dsmc/colliderbase.h \
		program/dsmc/moleculemover.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o program/dsmc/main.cpp

system.o: program/dsmc/system.cpp program/dsmc/system.h \
		program/dsmc/cinifile.h \
		program/dsmc/cutil.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/mpi.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/mpi_portable_platform.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/mpicxx.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/constants.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/functions.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/datatype.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/exception.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/op.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/status.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/request.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/group.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/comm.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/win.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/file.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/errhandler.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/intracomm.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/topology.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/intercomm.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/info.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/datatype_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/functions_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/request_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/comm_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/intracomm_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/topology_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/intercomm_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/group_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/op_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/errhandler_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/status_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/info_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/win_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/file_inln.h \
		program/dsmc/cell.h \
		program/dsmc/grid.h \
		program/dsmc/cvector.h \
		program/dsmc/topology.h \
		program/dsmc/random.h \
		program/dsmc/unitconverter.h \
		program/dsmc/dsmc_io.h \
		program/dsmc/settings.h \
		program/dsmc/moleculemover.h \
		program/dsmc/dsmctimer.h \
		program/dsmc/colliderbase.h \
		program/dsmc/colliderspecular.h \
		program/dsmc/colliderthermal.h \
		program/dsmc/collidercercignanilampis.h \
		program/dsmc/collidermaxwell.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o system.o program/dsmc/system.cpp

cell.o: program/dsmc/cell.cpp program/dsmc/cell.h \
		program/dsmc/system.h \
		program/dsmc/cinifile.h \
		program/dsmc/cutil.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/mpi.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/mpi_portable_platform.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/mpicxx.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/constants.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/functions.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/datatype.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/exception.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/op.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/status.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/request.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/group.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/comm.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/win.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/file.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/errhandler.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/intracomm.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/topology.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/intercomm.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/info.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/datatype_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/functions_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/request_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/comm_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/intracomm_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/topology_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/intercomm_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/group_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/op_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/errhandler_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/status_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/info_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/win_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/file_inln.h \
		program/dsmc/random.h \
		program/dsmc/settings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cell.o program/dsmc/cell.cpp

statisticssampler.o: program/dsmc/statisticssampler.cpp program/dsmc/statisticssampler.h \
		program/dsmc/cinifile.h \
		program/dsmc/cutil.h \
		program/dsmc/cell.h \
		program/dsmc/unitconverter.h \
		program/dsmc/dsmc_io.h \
		program/dsmc/system.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/mpi.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/mpi_portable_platform.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/mpicxx.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/constants.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/functions.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/datatype.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/exception.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/op.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/status.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/request.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/group.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/comm.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/win.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/file.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/errhandler.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/intracomm.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/topology.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/intercomm.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/info.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/datatype_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/functions_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/request_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/comm_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/intracomm_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/topology_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/intercomm_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/group_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/op_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/errhandler_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/status_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/info_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/win_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/file_inln.h \
		program/dsmc/settings.h \
		program/dsmc/moleculemover.h \
		program/dsmc/colliderbase.h \
		program/dsmc/dsmctimer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o statisticssampler.o program/dsmc/statisticssampler.cpp

random.o: program/dsmc/random.cpp program/dsmc/random.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o random.o program/dsmc/random.cpp

grid.o: program/dsmc/grid.cpp program/dsmc/grid.h \
		program/dsmc/cvector.h \
		program/dsmc/cutil.h \
		program/dsmc/system.h \
		program/dsmc/cinifile.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/mpi.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/mpi_portable_platform.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/mpicxx.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/constants.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/functions.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/datatype.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/exception.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/op.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/status.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/request.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/group.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/comm.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/win.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/file.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/errhandler.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/intracomm.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/topology.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/intercomm.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/info.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/datatype_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/functions_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/request_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/comm_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/intracomm_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/topology_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/intercomm_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/group_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/op_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/errhandler_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/status_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/info_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/win_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/file_inln.h \
		program/dsmc/topology.h \
		program/dsmc/dsmc_io.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o grid.o program/dsmc/grid.cpp

cutil.o: program/dsmc/cutil.cpp program/dsmc/cutil.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cutil.o program/dsmc/cutil.cpp

unitconverter.o: program/dsmc/unitconverter.cpp program/dsmc/unitconverter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o unitconverter.o program/dsmc/unitconverter.cpp

settings.o: program/dsmc/settings.cpp program/dsmc/settings.h \
		program/dsmc/cinifile.h \
		program/dsmc/cutil.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o settings.o program/dsmc/settings.cpp

dsmc_io.o: program/dsmc/dsmc_io.cpp program/dsmc/dsmc_io.h \
		program/dsmc/system.h \
		program/dsmc/cinifile.h \
		program/dsmc/cutil.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/mpi.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/mpi_portable_platform.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/mpicxx.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/constants.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/functions.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/datatype.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/exception.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/op.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/status.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/request.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/group.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/comm.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/win.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/file.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/errhandler.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/intracomm.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/topology.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/intercomm.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/info.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/datatype_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/functions_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/request_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/comm_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/intracomm_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/topology_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/intercomm_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/group_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/op_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/errhandler_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/status_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/info_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/win_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/file_inln.h \
		program/dsmc/cell.h \
		program/dsmc/grid.h \
		program/dsmc/cvector.h \
		program/dsmc/topology.h \
		program/dsmc/settings.h \
		program/dsmc/dsmctimer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dsmc_io.o program/dsmc/dsmc_io.cpp

dsmctimer.o: program/dsmc/dsmctimer.cpp program/dsmc/dsmctimer.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/mpi.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/mpi_portable_platform.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/mpicxx.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/constants.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/functions.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/datatype.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/exception.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/op.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/status.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/request.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/group.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/comm.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/win.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/file.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/errhandler.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/intracomm.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/topology.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/intercomm.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/info.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/datatype_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/functions_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/request_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/comm_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/intracomm_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/topology_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/intercomm_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/group_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/op_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/errhandler_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/status_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/info_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/win_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/file_inln.h \
		program/dsmc/system.h \
		program/dsmc/cinifile.h \
		program/dsmc/cutil.h \
		program/dsmc/topology.h \
		program/dsmc/dsmc_io.h \
		program/dsmc/settings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dsmctimer.o program/dsmc/dsmctimer.cpp

moleculemover.o: program/dsmc/moleculemover.cpp program/dsmc/moleculemover.h \
		program/dsmc/system.h \
		program/dsmc/cinifile.h \
		program/dsmc/cutil.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/mpi.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/mpi_portable_platform.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/mpicxx.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/constants.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/functions.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/datatype.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/exception.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/op.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/status.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/request.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/group.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/comm.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/win.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/file.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/errhandler.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/intracomm.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/topology.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/intercomm.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/info.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/datatype_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/functions_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/request_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/comm_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/intracomm_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/topology_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/intercomm_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/group_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/op_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/errhandler_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/status_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/info_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/win_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/file_inln.h \
		program/dsmc/cell.h \
		program/dsmc/grid.h \
		program/dsmc/cvector.h \
		program/dsmc/topology.h \
		program/dsmc/random.h \
		program/dsmc/settings.h \
		program/dsmc/colliderbase.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moleculemover.o program/dsmc/moleculemover.cpp

colliderbase.o: program/dsmc/colliderbase.cpp program/dsmc/colliderbase.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o colliderbase.o program/dsmc/colliderbase.cpp

colliderspecular.o: program/dsmc/colliderspecular.cpp program/dsmc/colliderspecular.h \
		program/dsmc/colliderbase.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o colliderspecular.o program/dsmc/colliderspecular.cpp

colliderthermal.o: program/dsmc/colliderthermal.cpp program/dsmc/colliderthermal.h \
		program/dsmc/colliderbase.h \
		program/dsmc/random.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o colliderthermal.o program/dsmc/colliderthermal.cpp

collidercercignanilampis.o: program/dsmc/collidercercignanilampis.cpp program/dsmc/collidercercignanilampis.h \
		program/dsmc/colliderbase.h \
		program/dsmc/random.h \
		program/dsmc/system.h \
		program/dsmc/cinifile.h \
		program/dsmc/cutil.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/mpi.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/mpi_portable_platform.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/mpicxx.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/constants.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/functions.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/datatype.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/exception.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/op.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/status.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/request.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/group.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/comm.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/win.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/file.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/errhandler.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/intracomm.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/topology.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/intercomm.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/info.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/datatype_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/functions_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/request_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/comm_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/intracomm_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/topology_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/intercomm_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/group_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/op_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/errhandler_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/status_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/info_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/win_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/file_inln.h \
		program/dsmc/unitconverter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o collidercercignanilampis.o program/dsmc/collidercercignanilampis.cpp

collidermaxwell.o: program/dsmc/collidermaxwell.cpp program/dsmc/collidermaxwell.h \
		program/dsmc/colliderbase.h \
		program/dsmc/random.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o collidermaxwell.o program/dsmc/collidermaxwell.cpp

cvector.o: program/dsmc/cvector.cpp program/dsmc/cvector.h \
		program/dsmc/cutil.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cvector.o program/dsmc/cvector.cpp

topology.o: program/dsmc/topology.cpp program/dsmc/topology.h \
		program/dsmc/system.h \
		program/dsmc/cinifile.h \
		program/dsmc/cutil.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/mpi.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/mpi_portable_platform.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/mpicxx.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/constants.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/functions.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/datatype.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/exception.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/op.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/status.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/request.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/group.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/comm.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/win.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/file.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/errhandler.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/intracomm.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/topology.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/intercomm.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/info.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/datatype_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/functions_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/request_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/comm_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/intracomm_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/topology_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/intercomm_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/group_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/op_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/errhandler_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/status_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/info_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/win_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/file_inln.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o topology.o program/dsmc/topology.cpp

visualizer.o: program/dsmc/visualizer.cpp program/dsmc/visualizer.h \
		program/dsmc/copengl.h \
		/usr/local/Cellar/glew/1.9.0/include/GL/glew.h \
		/usr/local/Cellar/glfw/2.7.8/include/GL/glfw.h \
		program/dsmc/oglshader.h \
		program/dsmc/cutil.h \
		program/dsmc/cvector.h \
		program/dsmc/fpsmanager.hpp \
		program/dsmc/camera.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o visualizer.o program/dsmc/visualizer.cpp

testshader.o: program/dsmc/testshader.cpp program/dsmc/testshader.h \
		program/dsmc/cshaders.h \
		program/dsmc/copengl.h \
		/usr/local/Cellar/glew/1.9.0/include/GL/glew.h \
		/usr/local/Cellar/glfw/2.7.8/include/GL/glfw.h \
		program/dsmc/oglshader.h \
		program/dsmc/cutil.h \
		program/dsmc/cvector.h \
		program/dsmc/fpsmanager.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o testshader.o program/dsmc/testshader.cpp

solver.o: program/dsmc/solver.cpp program/dsmc/solver.h \
		program/dsmc/system.h \
		program/dsmc/cinifile.h \
		program/dsmc/cutil.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/mpi.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/mpi_portable_platform.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/mpicxx.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/constants.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/functions.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/datatype.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/exception.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/op.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/status.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/request.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/group.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/comm.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/win.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/file.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/errhandler.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/intracomm.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/topology.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/intercomm.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/info.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/datatype_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/functions_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/request_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/comm_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/intracomm_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/topology_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/intercomm_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/group_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/op_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/errhandler_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/status_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/info_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/win_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/file_inln.h \
		program/dsmc/settings.h \
		program/dsmc/moleculemover.h \
		program/dsmc/colliderbase.h \
		program/dsmc/statisticssampler.h \
		program/dsmc/dsmc_io.h \
		program/dsmc/dsmctimer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o solver.o program/dsmc/solver.cpp

progressbar.o: program/dsmc/progressbar.cpp program/dsmc/progressbar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o progressbar.o program/dsmc/progressbar.cpp

perlin.o: program/dsmc/perlin.cpp program/dsmc/perlin.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o perlin.o program/dsmc/perlin.cpp

oglshader.o: program/dsmc/oglshader.cpp program/dsmc/oglshader.h \
		/usr/local/Cellar/glew/1.9.0/include/GL/glew.h \
		program/dsmc/cutil.h \
		program/dsmc/cvector.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o oglshader.o program/dsmc/oglshader.cpp

moviedata.o: program/dsmc/moviedata.cpp program/dsmc/moviedata.h \
		program/dsmc/defines.h \
		program/dsmc/cvector.h \
		program/dsmc/cutil.h \
		program/dsmc/system.h \
		program/dsmc/cinifile.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/mpi.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/mpi_portable_platform.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/mpicxx.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/constants.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/functions.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/datatype.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/exception.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/op.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/status.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/request.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/group.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/comm.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/win.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/file.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/errhandler.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/intracomm.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/topology.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/intercomm.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/info.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/datatype_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/functions_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/request_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/comm_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/intracomm_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/topology_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/intercomm_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/group_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/op_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/errhandler_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/status_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/info_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/win_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/file_inln.h \
		program/dsmc/solver.h \
		/usr/local/Cellar/glfw/2.7.8/include/GL/glfw.h \
		program/dsmc/ctexture.h \
		program/dsmc/cbitmap.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moviedata.o program/dsmc/moviedata.cpp

movie.o: program/dsmc/movie.cpp program/dsmc/defines.h \
		program/dsmc/visualizer.h \
		program/dsmc/copengl.h \
		/usr/local/Cellar/glew/1.9.0/include/GL/glew.h \
		/usr/local/Cellar/glfw/2.7.8/include/GL/glfw.h \
		program/dsmc/oglshader.h \
		program/dsmc/cutil.h \
		program/dsmc/cvector.h \
		program/dsmc/fpsmanager.hpp \
		program/dsmc/ctexture.h \
		program/dsmc/cbitmap.h \
		program/dsmc/cinifile.h \
		program/dsmc/marchingcubes.h \
		program/dsmc/mesh.h \
		program/dsmc/cshaders.h \
		program/dsmc/testshader.h \
		program/dsmc/complexgeometry.h \
		program/dsmc/moviedata.h \
		program/dsmc/camera.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o movie.o program/dsmc/movie.cpp

mesh.o: program/dsmc/mesh.cpp program/dsmc/mesh.h \
		program/dsmc/defines.h \
		program/dsmc/cshaders.h \
		program/dsmc/copengl.h \
		/usr/local/Cellar/glew/1.9.0/include/GL/glew.h \
		/usr/local/Cellar/glfw/2.7.8/include/GL/glfw.h \
		program/dsmc/oglshader.h \
		program/dsmc/cutil.h \
		program/dsmc/cvector.h \
		program/dsmc/fpsmanager.hpp \
		program/dsmc/testshader.h \
		program/dsmc/progressbar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mesh.o program/dsmc/mesh.cpp

marchingcubes.o: program/dsmc/marchingcubes.cpp program/dsmc/marchingcubes.h \
		program/dsmc/mesh.h \
		program/dsmc/defines.h \
		program/dsmc/cshaders.h \
		program/dsmc/copengl.h \
		/usr/local/Cellar/glew/1.9.0/include/GL/glew.h \
		/usr/local/Cellar/glfw/2.7.8/include/GL/glfw.h \
		program/dsmc/oglshader.h \
		program/dsmc/cutil.h \
		program/dsmc/cvector.h \
		program/dsmc/fpsmanager.hpp \
		program/dsmc/testshader.h \
		program/dsmc/progressbar.h \
		program/dsmc/complexgeometry.h \
		program/dsmc/random.h \
		program/dsmc/cisosurface.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o marchingcubes.o program/dsmc/marchingcubes.cpp

ctexture.o: program/dsmc/ctexture.cpp program/dsmc/copengl.h \
		/usr/local/Cellar/glew/1.9.0/include/GL/glew.h \
		/usr/local/Cellar/glfw/2.7.8/include/GL/glfw.h \
		program/dsmc/oglshader.h \
		program/dsmc/cutil.h \
		program/dsmc/cvector.h \
		program/dsmc/fpsmanager.hpp \
		program/dsmc/ctexture.h \
		program/dsmc/cbitmap.h \
		program/dsmc/camera.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/mpi.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/mpi_portable_platform.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/mpicxx.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/constants.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/functions.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/datatype.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/exception.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/op.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/status.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/request.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/group.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/comm.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/win.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/file.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/errhandler.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/intracomm.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/topology.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/intercomm.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/info.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/datatype_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/functions_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/request_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/comm_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/intracomm_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/topology_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/intercomm_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/group_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/op_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/errhandler_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/status_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/info_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/win_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/file_inln.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ctexture.o program/dsmc/ctexture.cpp

cshaders.o: program/dsmc/cshaders.cpp program/dsmc/cshaders.h \
		program/dsmc/copengl.h \
		/usr/local/Cellar/glew/1.9.0/include/GL/glew.h \
		/usr/local/Cellar/glfw/2.7.8/include/GL/glfw.h \
		program/dsmc/oglshader.h \
		program/dsmc/cutil.h \
		program/dsmc/cvector.h \
		program/dsmc/fpsmanager.hpp \
		program/dsmc/camera.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cshaders.o program/dsmc/cshaders.cpp

copengl.o: program/dsmc/copengl.cpp program/dsmc/copengl.h \
		/usr/local/Cellar/glew/1.9.0/include/GL/glew.h \
		/usr/local/Cellar/glfw/2.7.8/include/GL/glfw.h \
		program/dsmc/oglshader.h \
		program/dsmc/cutil.h \
		program/dsmc/cvector.h \
		program/dsmc/fpsmanager.hpp \
		program/dsmc/cmath.h \
		program/dsmc/cmatrix.h \
		program/dsmc/camera.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o copengl.o program/dsmc/copengl.cpp

complexgeometry.o: program/dsmc/complexgeometry.cpp program/dsmc/complexgeometry.h \
		program/dsmc/cvector.h \
		program/dsmc/cutil.h \
		program/dsmc/perlin.h \
		program/dsmc/progressbar.h \
		program/dsmc/random.h \
		program/dsmc/cinifile.h \
		program/dsmc/diamondsquare.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o complexgeometry.o program/dsmc/complexgeometry.cpp

combined.o: program/dsmc/combined.cpp program/dsmc/defines.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/mpi.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/mpi_portable_platform.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/mpicxx.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/constants.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/functions.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/datatype.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/exception.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/op.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/status.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/request.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/group.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/comm.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/win.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/file.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/errhandler.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/intracomm.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/topology.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/intercomm.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/info.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/datatype_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/functions_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/request_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/comm_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/intracomm_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/topology_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/intercomm_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/group_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/op_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/errhandler_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/status_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/info_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/win_inln.h \
		/usr/local/Cellar/open-mpi/1.6.4/include/openmpi/ompi/mpi/cxx/file_inln.h \
		program/dsmc/solver.h \
		program/dsmc/system.h \
		program/dsmc/cinifile.h \
		program/dsmc/cutil.h \
		program/dsmc/visualizer.h \
		program/dsmc/copengl.h \
		/usr/local/Cellar/glew/1.9.0/include/GL/glew.h \
		/usr/local/Cellar/glfw/2.7.8/include/GL/glfw.h \
		program/dsmc/oglshader.h \
		program/dsmc/cvector.h \
		program/dsmc/fpsmanager.hpp \
		program/dsmc/ctexture.h \
		program/dsmc/cbitmap.h \
		program/dsmc/marchingcubes.h \
		program/dsmc/mesh.h \
		program/dsmc/cshaders.h \
		program/dsmc/testshader.h \
		program/dsmc/complexgeometry.h \
		program/dsmc/moviedata.h \
		program/dsmc/camera.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o combined.o program/dsmc/combined.cpp

cmath.o: program/dsmc/cmath.cpp program/dsmc/cmath.h \
		program/dsmc/cmatrix.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cmath.o program/dsmc/cmath.cpp

citmap.o: program/dsmc/citmap.cpp program/dsmc/cbitmap.h \
		program/dsmc/cutil.h \
		program/dsmc/cvector.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o citmap.o program/dsmc/citmap.cpp

cisosurface.o: program/dsmc/cisosurface.cpp program/dsmc/cisosurface.h \
		program/dsmc/cvector.h \
		program/dsmc/cutil.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cisosurface.o program/dsmc/cisosurface.cpp

cbitmap.o: program/dsmc/cbitmap.cpp program/dsmc/cbitmap.h \
		program/dsmc/cutil.h \
		program/dsmc/cvector.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cbitmap.o program/dsmc/cbitmap.cpp

camera.o: program/dsmc/camera.cpp program/dsmc/camera.h \
		/usr/local/Cellar/glfw/2.7.8/include/GL/glfw.h \
		program/dsmc/cvector.h \
		program/dsmc/cutil.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o camera.o program/dsmc/camera.cpp

geometry.o: program/dsmc/geometry.cpp program/dsmc/defines.h \
		program/dsmc/visualizer.h \
		program/dsmc/copengl.h \
		/usr/local/Cellar/glew/1.9.0/include/GL/glew.h \
		/usr/local/Cellar/glfw/2.7.8/include/GL/glfw.h \
		program/dsmc/oglshader.h \
		program/dsmc/cutil.h \
		program/dsmc/cvector.h \
		program/dsmc/fpsmanager.hpp \
		program/dsmc/ctexture.h \
		program/dsmc/cbitmap.h \
		program/dsmc/testshader.h \
		program/dsmc/cshaders.h \
		program/dsmc/camera.h \
		program/dsmc/complexgeometry.h \
		program/dsmc/cinifile.h \
		program/dsmc/marchingcubes.h \
		program/dsmc/mesh.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o geometry.o program/dsmc/geometry.cpp

diamondsquare.o: program/dsmc/diamondsquare.cpp program/dsmc/diamondsquare.h \
		program/dsmc/random.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o diamondsquare.o program/dsmc/diamondsquare.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

